server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/css,application/javascript,application/json,image/svg+xml,application/font-woff2

spring:
  datasource:
    url: jdbc:postgresql://DB_HOST:5432/DB_NAME
    username: DB_USER
    password: DB_PASS
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      change-log: classpath:db/changelog/db.changelog-master.yaml
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
  web:
    resources:
      # Раздаём из classpath:/static (туда мы копируем Quasar dist)
      static-locations: classpath:/static/
      cache:
        period: 365d
      chain:
        cache: true
        compressed: true
logging:
  level:
    ru.baikalsr.backend: DEBUG
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    path: /v3/api-docs
security:
  jwt:
    secret: ${JWT_SECRET:dev-secret-change-me}
    ttl-seconds: ${JWT_TTL_SECONDS:3600}
    issuer: mdm-backend
app:
  admin:
    username: ${APP_ADMIN_USERNAME:Administrator}
    password: ${APP_ADMIN_PASSWORD:admin}
# (опционально) health-проверки
management:
  health:
    ldap:
      enabled: false